# Generated by Django 3.1.3 on 2021-12-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('age', models.TextField()),
                ('poto', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
